var rangersScheduleApp = angular.module('rangersScheduleApp', ['RangersScheduleFilter']);

rangersScheduleApp.controller('RangersScheduleCtrl', function ($scope) {
	$scope.games = [
		{ 'Date': '2016-04-09', 'Time': '8:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'Angels', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-04-10', 'Time': '2:35 PM', 'Opponent': 'LAA', 'Opponent_Full': 'Angels', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-04-11', 'Time': '9:10 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Mariners', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-04-12', 'Time': '9:10 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Mariners', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-04-13', 'Time': '2:40 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Mariners', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-04-14', 'Time': '7:05 PM', 'Opponent': 'BAL', 'Opponent_Full': 'Orioles', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-04-15', 'Time': '7:05 PM', 'Opponent': 'BAL', 'Opponent_Full': 'Orioles', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-04-16', 'Time': '7:05 PM', 'Opponent': 'BAL', 'Opponent_Full': 'Orioles', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-04-17', 'Time': '2:05 PM', 'Opponent': 'BAL', 'Opponent_Full': 'Orioles', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-04-19', 'Time': '7:05 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Astros', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-04-20', 'Time': '7:05 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Astros', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-04-21', 'Time': '7:05 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Astros', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-04-22', 'Time': '7:10 PM', 'Opponent': 'CWS', 'Opponent_Full': 'White Sox', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-04-23', 'Time': '1:10 PM', 'Opponent': 'CWS', 'Opponent_Full': 'White Sox', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-04-24', 'Time': '1:10 PM', 'Opponent': 'CWS', 'Opponent_Full': 'White Sox', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-04-25', 'Time': '7:05 PM', 'Opponent': 'NYY', 'Opponent_Full': 'Yankees', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-04-26', 'Time': '7:05 PM', 'Opponent': 'NYY', 'Opponent_Full': 'Yankees', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-04-27', 'Time': '7:05 PM', 'Opponent': 'NYY', 'Opponent_Full': 'Yankees', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-04-29', 'Time': '7:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'Angels', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-04-30', 'Time': '7:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'Angels', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-05-01', 'Time': '2:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'Angels', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-05-02', 'Time': '6:07 PM', 'Opponent': 'TOR', 'Opponent_Full': 'Blue Jays', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-05-03', 'Time': '6:07 PM', 'Opponent': 'TOR', 'Opponent_Full': 'Blue Jays', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-05-04', 'Time': '6:07 PM', 'Opponent': 'TOR', 'Opponent_Full': 'Blue Jays', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-05-05', 'Time': '6:07 PM', 'Opponent': 'TOR', 'Opponent_Full': 'Blue Jays', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-05-06', 'Time': '6:10 PM', 'Opponent': 'DET', 'Opponent_Full': 'Tigers', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-05-07', 'Time': '12:10 PM', 'Opponent': 'DET', 'Opponent_Full': 'Tigers', 'home': false, 'TV': 'FS1' },
		{ 'Date': '2016-05-08', 'Time': '12:10 PM', 'Opponent': 'DET', 'Opponent_Full': 'Tigers', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-05-09', 'Time': '7:05 PM', 'Opponent': 'CWS', 'Opponent_Full': 'White Sox', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-05-10', 'Time': '7:05 PM', 'Opponent': 'CWS', 'Opponent_Full': 'White Sox', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-05-11', 'Time': '1:05 PM', 'Opponent': 'CWS', 'Opponent_Full': 'White Sox', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-05-13', 'Time': '7:05 PM', 'Opponent': 'TOR', 'Opponent_Full': 'Blue Jays', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-05-14', 'Time': '7:05 PM', 'Opponent': 'TOR', 'Opponent_Full': 'Blue Jays', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-05-15', 'Time': '2:05 PM', 'Opponent': 'TOR', 'Opponent_Full': 'Blue Jays', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-05-16', 'Time': '9:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Athletics', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-05-17', 'Time': '9:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Athletics', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-05-18', 'Time': '2:35 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Athletics', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-05-20', 'Time': '7:10 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Astros', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-05-21', 'Time': '6:15 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Astros', 'home': false, 'TV': 'FOX' },
		{ 'Date': '2016-05-22', 'Time': '1:10 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Astros', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-05-23', 'Time': '7:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'Angels', 'home': false, 'TV': 'FS1' },
		{ 'Date': '2016-05-24', 'Time': '7:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'Angels', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-05-25', 'Time': '1:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'Angels', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-05-27', 'Time': '7:05 PM', 'Opponent': 'PIT', 'Opponent_Full': 'Pirates', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-05-28', 'Time': '6:15 PM', 'Opponent': 'PIT', 'Opponent_Full': 'Pirates', 'home': false, 'TV': 'FOX' },
		{ 'Date': '2016-05-29', 'Time': '2:05 PM', 'Opponent': 'PIT', 'Opponent_Full': 'Pirates', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-05-30', 'Time': '5:10 PM', 'Opponent': 'CLE', 'Opponent_Full': 'Indians', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-05-31', 'Time': '5:10 PM', 'Opponent': 'CLE', 'Opponent_Full': 'Indians', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-01', 'Time': '5:10 PM', 'Opponent': 'CLE', 'Opponent_Full': 'Indians', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-03', 'Time': '7:05 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Mariners', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-04', 'Time': '8:05 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Mariners', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-05', 'Time': '2:05 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Mariners', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-06', 'Time': '7:05 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Astros', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-07', 'Time': '7:05 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Astros', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-08', 'Time': '7:05 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Astros', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-09', 'Time': '1:05 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Astros', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-10', 'Time': '9:10 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Mariners', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-11', 'Time': '9:10 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Mariners', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-12', 'Time': '3:10 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Mariners', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-13', 'Time': '9:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Athletics', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-14', 'Time': '9:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Athletics', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-15', 'Time': '9:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Athletics', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-16', 'Time': '2:35 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Athletics', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-17', 'Time': '7:15 PM', 'Opponent': 'STL', 'Opponent_Full': 'Cardinals', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-18', 'Time': '3:15 PM', 'Opponent': 'STL', 'Opponent_Full': 'Cardinals', 'home': false, 'TV': 'FS1' },
		{ 'Date': '2016-06-19', 'Time': '1:15 PM', 'Opponent': 'STL', 'Opponent_Full': 'Cardinals', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-21', 'Time': '7:05 PM', 'Opponent': 'CIN', 'Opponent_Full': 'Reds', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-22', 'Time': '7:05 PM', 'Opponent': 'CIN', 'Opponent_Full': 'Reds', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-24', 'Time': '7:05 PM', 'Opponent': 'BOS', 'Opponent_Full': 'Red Sox', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-25', 'Time': '8:20 PM', 'Opponent': 'BOS', 'Opponent_Full': 'Red Sox', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-26', 'Time': '2:05 PM', 'Opponent': 'BOS', 'Opponent_Full': 'Red Sox', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-27', 'Time': '6:05 PM', 'Opponent': 'NYY', 'Opponent_Full': 'Yankees', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-28', 'Time': '6:05 PM', 'Opponent': 'NYY', 'Opponent_Full': 'Yankees', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-29', 'Time': '6:05 PM', 'Opponent': 'NYY', 'Opponent_Full': 'Yankees', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-06-30', 'Time': '12:05 PM', 'Opponent': 'NYY', 'Opponent_Full': 'Yankees', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-07-01', 'Time': '7:10 PM', 'Opponent': 'MIN', 'Opponent_Full': 'Twins', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-07-02', 'Time': '1:10 PM', 'Opponent': 'MIN', 'Opponent_Full': 'Twins', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-07-03', 'Time': '1:10 PM', 'Opponent': 'MIN', 'Opponent_Full': 'Twins', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-07-04', 'Time': '12:35 PM', 'Opponent': 'BOS', 'Opponent_Full': 'Red Sox', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-07-05', 'Time': '6:10 PM', 'Opponent': 'BOS', 'Opponent_Full': 'Red Sox', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-07-06', 'Time': '6:10 PM', 'Opponent': 'BOS', 'Opponent_Full': 'Red Sox', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-07-07', 'Time': '7:05 PM', 'Opponent': 'MIN', 'Opponent_Full': 'Twins', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-07-08', 'Time': '7:05 PM', 'Opponent': 'MIN', 'Opponent_Full': 'Twins', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-07-09', 'Time': '8:05 PM', 'Opponent': 'MIN', 'Opponent_Full': 'Twins', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-07-10', 'Time': '2:05 PM', 'Opponent': 'MIN', 'Opponent_Full': 'Twins', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-07-15', 'Time': '1:20 PM', 'Opponent': 'CHI', 'Opponent_Full': 'Cubs', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-07-16', 'Time': '1:20 PM', 'Opponent': 'CHI', 'Opponent_Full': 'Cubs', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-07-17', 'Time': '1:20 PM', 'Opponent': 'CHI', 'Opponent_Full': 'Cubs', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-07-18', 'Time': '9:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'Angels', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-07-19', 'Time': '9:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'Angels', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-07-20', 'Time': '9:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'Angels', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-07-22', 'Time': '7:15 PM', 'Opponent': 'KC', 'Opponent_Full': 'Royals', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-07-23', 'Time': '6:15 PM', 'Opponent': 'KC', 'Opponent_Full': 'Royals', 'home': false, 'TV': 'FS1' },
		{ 'Date': '2016-07-24', 'Time': '1:15 PM', 'Opponent': 'KC', 'Opponent_Full': 'Royals', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-07-25', 'Time': '7:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Athletics', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-07-26', 'Time': '7:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Athletics', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-07-27', 'Time': '7:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Athletics', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-07-28', 'Time': '7:05 PM', 'Opponent': 'KC', 'Opponent_Full': 'Royals', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-07-29', 'Time': '7:05 PM', 'Opponent': 'KC', 'Opponent_Full': 'Royals', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-07-30', 'Time': '7:05 PM', 'Opponent': 'KC', 'Opponent_Full': 'Royals', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-07-31', 'Time': '2:05 PM', 'Opponent': 'KC', 'Opponent_Full': 'Royals', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-02', 'Time': '6:05 PM', 'Opponent': 'BAL', 'Opponent_Full': 'Orioles', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-03', 'Time': '6:05 PM', 'Opponent': 'BAL', 'Opponent_Full': 'Orioles', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-04', 'Time': '6:05 PM', 'Opponent': 'BAL', 'Opponent_Full': 'Orioles', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-05', 'Time': '7:10 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Astros', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-06', 'Time': '6:10 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Astros', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-07', 'Time': '1:10 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Astros', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-08', 'Time': '7:40 PM', 'Opponent': 'COL', 'Opponent_Full': 'Rockies', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-09', 'Time': '2:10 PM', 'Opponent': 'COL', 'Opponent_Full': 'Rockies', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-10', 'Time': '7:05 PM', 'Opponent': 'COL', 'Opponent_Full': 'Rockies', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-11', 'Time': '1:05 PM', 'Opponent': 'COL', 'Opponent_Full': 'Rockies', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-12', 'Time': '7:05 PM', 'Opponent': 'DET', 'Opponent_Full': 'Tigers', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-13', 'Time': '7:05 PM', 'Opponent': 'DET', 'Opponent_Full': 'Tigers', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-14', 'Time': '2:05 PM', 'Opponent': 'DET', 'Opponent_Full': 'Tigers', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-15', 'Time': '7:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Athletics', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-16', 'Time': '7:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Athletics', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-17', 'Time': '7:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Athletics', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-19', 'Time': '6:10 PM', 'Opponent': 'TB', 'Opponent_Full': 'Rays', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-20', 'Time': '5:10 PM', 'Opponent': 'TB', 'Opponent_Full': 'Rays', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-21', 'Time': '12:10 PM', 'Opponent': 'TB', 'Opponent_Full': 'Rays', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-23', 'Time': '6:10 PM', 'Opponent': 'CIN', 'Opponent_Full': 'Reds', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-24', 'Time': '6:10 PM', 'Opponent': 'CIN', 'Opponent_Full': 'Reds', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-25', 'Time': '7:05 PM', 'Opponent': 'CLE', 'Opponent_Full': 'Indians', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-26', 'Time': '7:05 PM', 'Opponent': 'CLE', 'Opponent_Full': 'Indians', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-27', 'Time': '7:05 PM', 'Opponent': 'CLE', 'Opponent_Full': 'Indians', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-28', 'Time': '2:05 PM', 'Opponent': 'CLE', 'Opponent_Full': 'Indians', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-29', 'Time': '7:05 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Mariners', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-30', 'Time': '7:05 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Mariners', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-08-31', 'Time': '1:05 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Mariners', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-02', 'Time': '7:05 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Astros', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-03', 'Time': '3:05 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Astros', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-04', 'Time': '2:05 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Astros', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-05', 'Time': '3:10 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Mariners', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-06', 'Time': '9:10 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Mariners', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-07', 'Time': '9:10 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Mariners', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-08', 'Time': '9:10 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Mariners', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-09', 'Time': '9:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'Angels', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-10', 'Time': '8:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'Angels', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-11', 'Time': '12:00 PM', 'Opponent': 'LAA', 'Opponent_Full': 'Angels', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-12', 'Time': '7:10 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Astros', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-13', 'Time': '7:10 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Astros', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-14', 'Time': '7:10 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Astros', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-16', 'Time': '7:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Athletics', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-17', 'Time': '7:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Athletics', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-18', 'Time': '2:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Athletics', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-19', 'Time': '7:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'Angels', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-20', 'Time': '7:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'Angels', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-21', 'Time': '7:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'Angels', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-23', 'Time': '8:35 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Athletics', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-24', 'Time': '3:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Athletics', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-25', 'Time': '3:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Athletics', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-26', 'Time': '7:05 PM', 'Opponent': 'MIL', 'Opponent_Full': 'Brewers', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-27', 'Time': '7:05 PM', 'Opponent': 'MIL', 'Opponent_Full': 'Brewers', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-28', 'Time': '7:05 PM', 'Opponent': 'MIL', 'Opponent_Full': 'Brewers', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-09-30', 'Time': '7:05 PM', 'Opponent': 'TB', 'Opponent_Full': 'Rays', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-10-01', 'Time': '7:05 PM', 'Opponent': 'TB', 'Opponent_Full': 'Rays', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2016-10-02', 'Time': '2:05 PM', 'Opponent': 'TB', 'Opponent_Full': 'Rays', 'home': false, 'TV': 'FSSW' }
	];
});
