var rangersScheduleApp = angular.module('rangersScheduleApp', []);

rangersScheduleApp.controller('RangersScheduleCtrl', function ($scope) {
	$scope.games = [
		{ 'Date': '2014-03-31', 'Time': '1:05 PM', 'Opponent': 'PHI', 'Opponent_Full': 'Philadelphia', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-04-01', 'Time': '7:05 PM', 'Opponent': 'PHI', 'Opponent_Full': 'Philadelphia', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-04-02', 'Time': '7:05 PM', 'Opponent': 'PHI', 'Opponent_Full': 'Philadelphia', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-04-04', 'Time': '6:10 PM', 'Opponent': 'TB', 'Opponent_Full': 'Tampa Bay', 'home': false, 'TV': 'TXA-21' },
		{ 'Date': '2014-04-05', 'Time': '6:10 PM', 'Opponent': 'TB', 'Opponent_Full': 'Tampa Bay', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-04-06', 'Time': '12:40 PM', 'Opponent': 'TB', 'Opponent_Full': 'Tampa Bay', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-04-07', 'Time': '6:10 PM', 'Opponent': 'BOS', 'Opponent_Full': 'Boston', 'home': false, 'TV': 'FSSW, ESPN' },
		{ 'Date': '2014-04-08', 'Time': '5:10 PM', 'Opponent': 'BOS', 'Opponent_Full': 'Boston', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-04-09', 'Time': '3:05 PM', 'Opponent': 'BOS', 'Opponent_Full': 'Boston', 'home': false, 'TV': 'FSSW, MLBN' },
		{ 'Date': '2014-04-11', 'Time': '7:05 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Houston', 'home': true, 'TV': 'TXA-21' },
		{ 'Date': '2014-04-12', 'Time': '7:05 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Houston', 'home': true, 'TV': 'FSSW, MLBN' },
		{ 'Date': '2014-04-13', 'Time': '2:05 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Houston', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-04-14', 'Time': '7:05 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Seattle', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-04-15', 'Time': '7:05 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Seattle', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-04-16', 'Time': '7:05 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Seattle', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-04-17', 'Time': '1:05 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Seattle', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-04-18', 'Time': '7:05 PM', 'Opponent': 'CWS', 'Opponent_Full': 'Chi White Sox', 'home': true, 'TV': 'TXA-21' },
		{ 'Date': '2014-04-19', 'Time': '7:05 PM', 'Opponent': 'CWS', 'Opponent_Full': 'Chi White Sox', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-04-20', 'Time': '2:05 PM', 'Opponent': 'CWS', 'Opponent_Full': 'Chi White Sox', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-04-21', 'Time': '9:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Oakland', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-04-22', 'Time': '9:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Oakland', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-04-23', 'Time': '2:35 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Oakland', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-04-25', 'Time': '9:10 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Seattle', 'home': false, 'TV': 'TXA-21' },
		{ 'Date': '2014-04-26', 'Time': '8:10 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Seattle', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-04-27', 'Time': '3:10 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Seattle', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-04-28', 'Time': '7:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Oakland', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-04-29', 'Time': '7:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Oakland', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-04-30', 'Time': '7:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Oakland', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-05-02', 'Time': '9:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'LA Angels', 'home': false, 'TV': 'TXA-21' },
		{ 'Date': '2014-05-03', 'Time': '8:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'LA Angels', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-05-04', 'Time': '2:35 PM', 'Opponent': 'LAA', 'Opponent_Full': 'LA Angels', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-05-05', 'Time': '7:40 PM', 'Opponent': 'COL', 'Opponent_Full': 'Colorado', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-05-06', 'Time': '7:40 PM', 'Opponent': 'COL', 'Opponent_Full': 'Colorado', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-05-07', 'Time': '7:05 PM', 'Opponent': 'COL', 'Opponent_Full': 'Colorado', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-05-08', 'Time': '7:05 PM', 'Opponent': 'COL', 'Opponent_Full': 'Colorado', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-05-09', 'Time': '7:05 PM', 'Opponent': 'BOS', 'Opponent_Full': 'Boston', 'home': true, 'TV': 'TXA-21' },
		{ 'Date': '2014-05-10', 'Time': '7:05 PM', 'Opponent': 'BOS', 'Opponent_Full': 'Boston', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-05-11', 'Time': '2:05 PM', 'Opponent': 'BOS', 'Opponent_Full': 'Boston', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-05-12', 'Time': '7:10 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Houston', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-05-13', 'Time': '7:10 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Houston', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-05-14', 'Time': '7:10 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Houston', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-05-16', 'Time': '7:05 PM', 'Opponent': 'TOR', 'Opponent_Full': 'Toronto', 'home': true, 'TV': 'TXA-21' },
		{ 'Date': '2014-05-17', 'Time': '7:05 PM', 'Opponent': 'TOR', 'Opponent_Full': 'Toronto', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-05-18', 'Time': '2:05 PM', 'Opponent': 'TOR', 'Opponent_Full': 'Toronto', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-05-20', 'Time': '7:05 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Seattle', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-05-21', 'Time': '1:05 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Seattle', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-05-22', 'Time': '12:08 PM', 'Opponent': 'DET', 'Opponent_Full': 'Detroit', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-05-23', 'Time': '6:08 PM', 'Opponent': 'DET', 'Opponent_Full': 'Detroit', 'home': false, 'TV': 'TXA-21' },
		{ 'Date': '2014-05-24', 'Time': '3:08 PM', 'Opponent': 'DET', 'Opponent_Full': 'Detroit', 'home': false, 'TV': 'FS1' },
		{ 'Date': '2014-05-25', 'Time': '12:08 PM', 'Opponent': 'DET', 'Opponent_Full': 'Detroit', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-05-26', 'Time': '1:10 PM', 'Opponent': 'MIN', 'Opponent_Full': 'Minnesota', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-05-27', 'Time': '7:10 PM', 'Opponent': 'MIN', 'Opponent_Full': 'Minnesota', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-05-28', 'Time': '7:10 PM', 'Opponent': 'MIN', 'Opponent_Full': 'Minnesota', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-05-29', 'Time': '12:10 PM', 'Opponent': 'MIN', 'Opponent_Full': 'Minnesota', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-05-30', 'Time': '6:05 PM', 'Opponent': 'WSH', 'Opponent_Full': 'Washington', 'home': false, 'TV': 'TXA-21' },
		{ 'Date': '2014-05-31', 'Time': '11:05 AM', 'Opponent': 'WSH', 'Opponent_Full': 'Washington', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-06-01', 'Time': '12:35 PM', 'Opponent': 'WSH', 'Opponent_Full': 'Washington', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-06-03', 'Time': '7:05 PM', 'Opponent': 'BAL', 'Opponent_Full': 'Baltimore', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-06-04', 'Time': '7:05 PM', 'Opponent': 'BAL', 'Opponent_Full': 'Baltimore', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-06-05', 'Time': '7:05 PM', 'Opponent': 'BAL', 'Opponent_Full': 'Baltimore', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-06-06', 'Time': '7:05 PM', 'Opponent': 'CLE', 'Opponent_Full': 'Cleveland', 'home': true, 'TV': 'TXA-21' },
		{ 'Date': '2014-06-07', 'Time': '3:05 PM', 'Opponent': 'CLE', 'Opponent_Full': 'Cleveland', 'home': true, 'TV': 'FS1' },
		{ 'Date': '2014-06-08', 'Time': '2:05 PM', 'Opponent': 'CLE', 'Opponent_Full': 'Cleveland', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-06-09', 'Time': '7:05 PM', 'Opponent': 'CLE', 'Opponent_Full': 'Cleveland', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-06-10', 'Time': '7:05 PM', 'Opponent': 'MIA', 'Opponent_Full': 'Miami', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-06-11', 'Time': '7:05 PM', 'Opponent': 'MIA', 'Opponent_Full': 'Miami', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-06-13', 'Time': '9:10 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Seattle', 'home': false, 'TV': 'TXA-21' },
		{ 'Date': '2014-06-14', 'Time': '9:10 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Seattle', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-06-15', 'Time': '3:10 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Seattle', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-06-16', 'Time': '9:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Oakland', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-06-17', 'Time': '9:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Oakland', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-06-18', 'Time': '2:35 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Oakland', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-06-20', 'Time': '9:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'LA Angels', 'home': false, 'TV': 'TXA-21' },
		{ 'Date': '2014-06-21', 'Time': '9:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'LA Angels', 'home': false, 'TV': 'FS1' },
		{ 'Date': '2014-06-22', 'Time': 'TBD', 'Opponent': 'LAA', 'Opponent_Full': 'LA Angels', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-06-24', 'Time': '7:05 PM', 'Opponent': 'DET', 'Opponent_Full': 'Detroit', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-06-25', 'Time': '7:05 PM', 'Opponent': 'DET', 'Opponent_Full': 'Detroit', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-06-26', 'Time': '7:05 PM', 'Opponent': 'DET', 'Opponent_Full': 'Detroit', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-06-27', 'Time': '7:05 PM', 'Opponent': 'MIN', 'Opponent_Full': 'Minnesota', 'home': true, 'TV': 'TXA-21' },
		{ 'Date': '2014-06-28', 'Time': '3:05 PM', 'Opponent': 'MIN', 'Opponent_Full': 'Minnesota', 'home': true, 'TV': 'FS1' },
		{ 'Date': '2014-06-29', 'Time': '2:05 PM', 'Opponent': 'MIN', 'Opponent_Full': 'Minnesota', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-06-30', 'Time': '6:05 PM', 'Opponent': 'BAL', 'Opponent_Full': 'Baltimore', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-07-01', 'Time': '6:05 PM', 'Opponent': 'BAL', 'Opponent_Full': 'Baltimore', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-07-02', 'Time': '6:05 PM', 'Opponent': 'BAL', 'Opponent_Full': 'Baltimore', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-07-03', 'Time': '6:05 PM', 'Opponent': 'BAL', 'Opponent_Full': 'Baltimore', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-07-04', 'Time': '6:10 PM', 'Opponent': 'NYM', 'Opponent_Full': 'NY Mets', 'home': false, 'TV': 'TXA-21' },
		{ 'Date': '2014-07-05', 'Time': '6:15 PM', 'Opponent': 'NYM', 'Opponent_Full': 'NY Mets', 'home': false, 'TV': 'FOX' },
		{ 'Date': '2014-07-06', 'Time': '12:10 PM', 'Opponent': 'NYM', 'Opponent_Full': 'NY Mets', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-07-07', 'Time': '7:05 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Houston', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-07-08', 'Time': '7:05 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Houston', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-07-09', 'Time': '7:05 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Houston', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-07-10', 'Time': '7:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'LA Angels', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-07-11', 'Time': '7:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'LA Angels', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-07-12', 'Time': '6:15 PM', 'Opponent': 'LAA', 'Opponent_Full': 'LA Angels', 'home': true, 'TV': 'FOX' },
		{ 'Date': '2014-07-13', 'Time': '2:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'LA Angels', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-07-18', 'Time': '6:07 PM', 'Opponent': 'TOR', 'Opponent_Full': 'Toronto', 'home': false, 'TV': 'TXA-21' },
		{ 'Date': '2014-07-19', 'Time': '12:07 PM', 'Opponent': 'TOR', 'Opponent_Full': 'Toronto', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-07-20', 'Time': '12:07 PM', 'Opponent': 'TOR', 'Opponent_Full': 'Toronto', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-07-21', 'Time': '6:05 PM', 'Opponent': 'NYY', 'Opponent_Full': 'NY Yankees', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-07-22', 'Time': '6:05 PM', 'Opponent': 'NYY', 'Opponent_Full': 'NY Yankees', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-07-23', 'Time': '6:05 PM', 'Opponent': 'NYY', 'Opponent_Full': 'NY Yankees', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-07-24', 'Time': '12:05 PM', 'Opponent': 'NYY', 'Opponent_Full': 'NY Yankees', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-07-25', 'Time': '7:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Oakland', 'home': true, 'TV': 'TXA-21' },
		{ 'Date': '2014-07-26', 'Time': '7:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Oakland', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-07-27', 'Time': '6:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Oakland', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-07-28', 'Time': '7:05 PM', 'Opponent': 'NYY', 'Opponent_Full': 'NY Yankees', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-07-29', 'Time': '7:05 PM', 'Opponent': 'NYY', 'Opponent_Full': 'NY Yankees', 'home': true, 'TV': 'FS1' },
		{ 'Date': '2014-07-30', 'Time': '7:05 PM', 'Opponent': 'NYY', 'Opponent_Full': 'NY Yankees', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-08-01', 'Time': '6:05 PM', 'Opponent': 'CLE', 'Opponent_Full': 'Cleveland', 'home': false, 'TV': 'TXA-21' },
		{ 'Date': '2014-08-02', 'Time': '6:05 PM', 'Opponent': 'CLE', 'Opponent_Full': 'Cleveland', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-08-03', 'Time': '12:05 PM', 'Opponent': 'CLE', 'Opponent_Full': 'Cleveland', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-08-04', 'Time': '7:10 PM', 'Opponent': 'CWS', 'Opponent_Full': 'Chi White Sox', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-08-05', 'Time': '7:10 PM', 'Opponent': 'CWS', 'Opponent_Full': 'Chi White Sox', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-08-06', 'Time': '1:10 PM', 'Opponent': 'CWS', 'Opponent_Full': 'Chi White Sox', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-08-08', 'Time': '7:10 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Houston', 'home': false, 'TV': 'TXA-21' },
		{ 'Date': '2014-08-09', 'Time': '6:10 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Houston', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-08-10', 'Time': '1:10 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Houston', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-08-11', 'Time': '7:05 PM', 'Opponent': 'TB', 'Opponent_Full': 'Tampa Bay', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-08-12', 'Time': '7:05 PM', 'Opponent': 'TB', 'Opponent_Full': 'Tampa Bay', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-08-13', 'Time': '7:05 PM', 'Opponent': 'TB', 'Opponent_Full': 'Tampa Bay', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-08-14', 'Time': '7:05 PM', 'Opponent': 'TB', 'Opponent_Full': 'Tampa Bay', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-08-15', 'Time': '7:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'LA Angels', 'home': true, 'TV': 'TXA-21' },
		{ 'Date': '2014-08-16', 'Time': '7:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'LA Angels', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-08-17', 'Time': '2:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'LA Angels', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-08-19', 'Time': '6:10 PM', 'Opponent': 'MIA', 'Opponent_Full': 'Miami', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-08-20', 'Time': '11:40 AM', 'Opponent': 'MIA', 'Opponent_Full': 'Miami', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-08-22', 'Time': '7:05 PM', 'Opponent': 'KC', 'Opponent_Full': 'Kansas City', 'home': true, 'TV': 'TXA-21' },
		{ 'Date': '2014-08-23', 'Time': '7:05 PM', 'Opponent': 'KC', 'Opponent_Full': 'Kansas City', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-08-24', 'Time': '2:05 PM', 'Opponent': 'KC', 'Opponent_Full': 'Kansas City', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-08-25', 'Time': '9:10 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Seattle', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-08-26', 'Time': '9:10 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Seattle', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-08-27', 'Time': '2:40 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Seattle', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-08-28', 'Time': '7:10 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Houston', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-08-29', 'Time': '7:10 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Houston', 'home': false, 'TV': 'TXA-21' },
		{ 'Date': '2014-08-30', 'Time': '6:10 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Houston', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-08-31', 'Time': '1:10 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Houston', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-09-01', 'Time': '7:10 PM', 'Opponent': 'KC', 'Opponent_Full': 'Kansas City', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-09-02', 'Time': '7:10 PM', 'Opponent': 'KC', 'Opponent_Full': 'Kansas City', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-09-03', 'Time': '7:10 PM', 'Opponent': 'KC', 'Opponent_Full': 'Kansas City', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-09-04', 'Time': '7:05 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Seattle', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-09-05', 'Time': '7:05 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Seattle', 'home': true, 'TV': 'TXA-21' },
		{ 'Date': '2014-09-06', 'Time': '7:05 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Seattle', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-09-07', 'Time': '2:05 PM', 'Opponent': 'SEA', 'Opponent_Full': 'Seattle', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-09-09', 'Time': '7:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'LA Angels', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-09-10', 'Time': '7:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'LA Angels', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-09-11', 'Time': '7:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'LA Angels', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-09-12', 'Time': '7:05 PM', 'Opponent': 'ATL', 'Opponent_Full': 'Atlanta', 'home': true, 'TV': 'TXA-21' },
		{ 'Date': '2014-09-13', 'Time': '12:05 PM', 'Opponent': 'ATL', 'Opponent_Full': 'Atlanta', 'home': true, 'TV': 'FOX' },
		{ 'Date': '2014-09-14', 'Time': '2:05 PM', 'Opponent': 'ATL', 'Opponent_Full': 'Atlanta', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-09-16', 'Time': '9:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Oakland', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-09-17', 'Time': '9:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Oakland', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-09-18', 'Time': '2:35 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Oakland', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-09-19', 'Time': '9:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'LA Angels', 'home': false, 'TV': 'TXA-21' },
		{ 'Date': '2014-09-20', 'Time': '8:05 PM', 'Opponent': 'LAA', 'Opponent_Full': 'LA Angels', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-09-21', 'Time': 'TBD', 'Opponent': 'LAA', 'Opponent_Full': 'LA Angels', 'home': false, 'TV': 'FSSW' },
		{ 'Date': '2014-09-22', 'Time': '7:05 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Houston', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-09-23', 'Time': '7:05 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Houston', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-09-24', 'Time': '7:05 PM', 'Opponent': 'HOU', 'Opponent_Full': 'Houston', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-09-25', 'Time': '7:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Oakland', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-09-26', 'Time': '7:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Oakland', 'home': true, 'TV': 'TXA-21' },
		{ 'Date': '2014-09-27', 'Time': '7:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Oakland', 'home': true, 'TV': 'FSSW' },
		{ 'Date': '2014-09-28', 'Time': '2:05 PM', 'Opponent': 'OAK', 'Opponent_Full': 'Oakland', 'home': true, 'TV': 'FSSW' }
	];
});
